interface PrazoEntrega {
  cidade: string;
  prazoEntrega: number;
}

export const prazosEntrega: PrazoEntrega[] = [
  { cidade: "ABDON BATISTA", prazoEntrega: 4 },
  { cidade: "ABELARDO LUZ", prazoEntrega: 3 },
  { cidade: "AGROLANDIA", prazoEntrega: 2 },
  { cidade: "AGRONOMICA", prazoEntrega: 2 },
  { cidade: "AGUA DOCE", prazoEntrega: 3 },
  { cidade: "AGUAS DE CHAPECO", prazoEntrega: 2 },
  { cidade: "AGUAS FRIAS", prazoEntrega: 3 },
  { cidade: "AGUAS MORNAS", prazoEntrega: 3 },
  { cidade: "ALFREDO WAGNER", prazoEntrega: 3 },
  { cidade: "ALTO BELA VISTA", prazoEntrega: 3 },
  { cidade: "ANCHIETA", prazoEntrega: 2 },
  { cidade: "ANGELINA", prazoEntrega: 3 },
  { cidade: "ANITA GARIBALDI", prazoEntrega: 3 },
  { cidade: "ANITAPOLIS", prazoEntrega: 3 },
  { cidade: "ANTONIO CARLOS", prazoEntrega: 3 },
  { cidade: "APIUNA", prazoEntrega: 2 },
  { cidade: "ARABUTA", prazoEntrega: 3 },
  { cidade: "ARARANGUA", prazoEntrega: 2 },
  { cidade: "ARMAZEM", prazoEntrega: 3 },
  { cidade: "ARROIO TRINTA", prazoEntrega: 3 },
  { cidade: "ARVOREDO", prazoEntrega: 4 },
  { cidade: "ASCURRA", prazoEntrega: 2 },
  { cidade: "ATALANTA", prazoEntrega: 2 },
  { cidade: "AURORA", prazoEntrega: 2 },
  { cidade: "BALNEARIO ARROIO DO SILVA", prazoEntrega: 2 },
  { cidade: "BALNEARIO CAMBORIU", prazoEntrega: 1 },
  { cidade: "BALNEARIO GAIVOTA", prazoEntrega: 3 },
  { cidade: "BALNEARIO PICARRAS", prazoEntrega: 2 },
  { cidade: "BALNEARIO RINCAO", prazoEntrega: 3 },
  { cidade: "BANDEIRANTE", prazoEntrega: 3 },
  { cidade: "BARRA BONITA", prazoEntrega: 3 },
  { cidade: "BELMONTE", prazoEntrega: 3 },
  { cidade: "BENEDITO NOVO", prazoEntrega: 3 },
  { cidade: "BLUMENAU", prazoEntrega: 1 },
  { cidade: "BOCAINA DO SUL", prazoEntrega: 3 },
  { cidade: "BOM JARDIM DA SERRA", prazoEntrega: 3 },
  { cidade: "BOM JESUS", prazoEntrega: 3 },
  { cidade: "BOM JESUS DO OESTE", prazoEntrega: 2 },
  { cidade: "BOM RETIRO", prazoEntrega: 3 },
  { cidade: "BOMBINHAS", prazoEntrega: 2 },
  { cidade: "BOTUVERA", prazoEntrega: 4 },
  { cidade: "BRACO DO NORTE", prazoEntrega: 3 },
  { cidade: "BRACO DO TROMBUDO", prazoEntrega: 2 },
  { cidade: "BRUNOPOLIS", prazoEntrega: 5 },
  { cidade: "BRUSQUE", prazoEntrega: 2 },
  { cidade: "CACADOR", prazoEntrega: 2 },
  { cidade: "CAIBI", prazoEntrega: 2 },
  { cidade: "CALMON", prazoEntrega: 3 },
  { cidade: "CAMBORIU", prazoEntrega: 1 },
  { cidade: "CAMPO BELO DO SUL", prazoEntrega: 3 },
  { cidade: "CAMPO ERE", prazoEntrega: 2 },
  { cidade: "CAMPOS NOVOS", prazoEntrega: 2 },
  { cidade: "CANELINHA", prazoEntrega: 3 },
  { cidade: "CAPAO ALTO", prazoEntrega: 3 },
  { cidade: "CAPINZAL", prazoEntrega: 2 },
  { cidade: "CAPIVARI DE BAIXO", prazoEntrega: 2 },
  { cidade: "CATANDUVAS", prazoEntrega: 3 },
  { cidade: "CAXAMBU DO SUL", prazoEntrega: 2 },
  { cidade: "CELSO RAMOS", prazoEntrega: 3 },
  { cidade: "CERRO NEGRO", prazoEntrega: 4 },
  { cidade: "CHAPADAO DO LAGEADO", prazoEntrega: 2 },
  { cidade: "CHAPECO", prazoEntrega: 1 },
  { cidade: "COCAL DO SUL", prazoEntrega: 3 },
  { cidade: "CONCORDIA", prazoEntrega: 2 },
  { cidade: "CORDILHEIRA ALTA", prazoEntrega: 3 },
  { cidade: "CORONEL FREITAS", prazoEntrega: 2 },
  { cidade: "CORONEL MARTINS", prazoEntrega: 3 },
  { cidade: "CORREIA PINTO", prazoEntrega: 2 },
  { cidade: "CRICIUMA", prazoEntrega: 1 },
  { cidade: "CUNHA PORA", prazoEntrega: 3 },
  { cidade: "CUNHATAI", prazoEntrega: 3 },
  { cidade: "CURITIBANOS", prazoEntrega: 2 },
  { cidade: "DESCANSO", prazoEntrega: 2 },
  { cidade: "DIONISIO CERQUEIRA", prazoEntrega: 2 },
  { cidade: "DONA EMMA", prazoEntrega: 2 },
  { cidade: "DOUTOR PEDRINHO", prazoEntrega: 3 },
  { cidade: "ENTRE RIOS", prazoEntrega: 5 },
  { cidade: "ERMO", prazoEntrega: 3 },
  { cidade: "ERVAL VELHO", prazoEntrega: 3 },
  { cidade: "FAXINAL DOS GUEDES", prazoEntrega: 3 },
  { cidade: "FLOR DO SERTAO", prazoEntrega: 3 },
  { cidade: "FORMOSA DO SUL", prazoEntrega: 2 },
  { cidade: "FORQUILHINHA", prazoEntrega: 2 },
  { cidade: "FRAIBURGO", prazoEntrega: 3 },
  { cidade: "FREI ROGERIO", prazoEntrega: 3 },
  { cidade: "GALVAO", prazoEntrega: 2 },
  { cidade: "GAROPABA", prazoEntrega: 3 },
  { cidade: "GASPAR", prazoEntrega: 3 },
  { cidade: "GOVERNADOR CELSO RAMOS", prazoEntrega: 3 },
  { cidade: "GRAO PARA", prazoEntrega: 3 },
  { cidade: "GRAVATAL", prazoEntrega: 3 },
  { cidade: "GUABIRUBA", prazoEntrega: 5 },
  { cidade: "GUARACIABA", prazoEntrega: 2 },
  { cidade: "GUARUJA DO SUL", prazoEntrega: 2 },
  { cidade: "GUATAMBU", prazoEntrega: 3 },
  { cidade: "HERVAL D OESTE", prazoEntrega: 2 },
  { cidade: "IBIAM", prazoEntrega: 4 },
  { cidade: "IBICARE", prazoEntrega: 3 },
  { cidade: "IBIRAMA", prazoEntrega: 2 },
  { cidade: "ICARA", prazoEntrega: 2 },
  { cidade: "ILHOTA", prazoEntrega: 4 },
  { cidade: "IMARUI", prazoEntrega: 3 },
  { cidade: "IMBITUBA", prazoEntrega: 3 },
  { cidade: "IMBUIA", prazoEntrega: 2 },
  { cidade: "INDAIAL", prazoEntrega: 3 },
  { cidade: "IOMERE", prazoEntrega: 3 },
  { cidade: "IPIRA", prazoEntrega: 3 },
  { cidade: "IPORA DO OESTE", prazoEntrega: 2 },
  { cidade: "IPUACU", prazoEntrega: 3 },
  { cidade: "IPUMIRIM", prazoEntrega: 3 },
  { cidade: "IRACEMINHA", prazoEntrega: 3 },
  { cidade: "IRANI", prazoEntrega: 2 },
  { cidade: "IRATI", prazoEntrega: 4 },
  { cidade: "ITA", prazoEntrega: 3 },
  { cidade: "ITAJAI", prazoEntrega: 1 },
  { cidade: "ITAPEMA", prazoEntrega: 2 },
  { cidade: "ITAPIRANGA", prazoEntrega: 2 },
  { cidade: "ITUPORANGA", prazoEntrega: 2 },
  { cidade: "JABORA", prazoEntrega: 2 },
  { cidade: "JACINTO MACHADO", prazoEntrega: 3 },
  { cidade: "JAGUARUNA", prazoEntrega: 4 },
  { cidade: "JARDINOPOLIS", prazoEntrega: 3 },
  { cidade: "JOACABA", prazoEntrega: 1 },
  { cidade: "JOSE BOITEUX", prazoEntrega: 2 },
  { cidade: "JUPIA", prazoEntrega: 3 },
  { cidade: "LACERDOPOLIS", prazoEntrega: 3 },
  { cidade: "LAGES", prazoEntrega: 1 },
  { cidade: "LAGUNA", prazoEntrega: 3 },
  { cidade: "LAJEADO GRANDE", prazoEntrega: 4 },
  { cidade: "LAURENTINO", prazoEntrega: 2 },
  { cidade: "LAURO MULLER", prazoEntrega: 3 },
  { cidade: "LEBON REGIS", prazoEntrega: 4 },
  { cidade: "LEOBERTO LEAL", prazoEntrega: 2 },
  { cidade: "LINDOIA DO SUL", prazoEntrega: 3 },
  { cidade: "LONTRAS", prazoEntrega: 2 },
  { cidade: "LUIZ ALVES", prazoEntrega: 4 },
  { cidade: "LUZERNA", prazoEntrega: 2 },
  { cidade: "MACIEIRA", prazoEntrega: 3 },
  { cidade: "MAJOR GERCINO", prazoEntrega: 4 },
  { cidade: "MARACAJA", prazoEntrega: 3 },
  { cidade: "MARAVILHA", prazoEntrega: 2 },
  { cidade: "MAREMA", prazoEntrega: 3 },
  { cidade: "MATOS COSTA", prazoEntrega: 3 },
  { cidade: "MELEIRO", prazoEntrega: 4 },
  { cidade: "MIRIM DOCE", prazoEntrega: 2 },
  { cidade: "MODELO", prazoEntrega: 2 },
  { cidade: "MONDAI", prazoEntrega: 2 },
  { cidade: "MONTE CARLO", prazoEntrega: 3 },
  { cidade: "MORRO DA FUMACA", prazoEntrega: 2 },
  { cidade: "MORRO GRANDE", prazoEntrega: 4 },
  { cidade: "NAVEGANTES", prazoEntrega: 2 },
  { cidade: "NOVA ERECHIM", prazoEntrega: 2 },
  { cidade: "NOVA ITABERABA", prazoEntrega: 4 },
  { cidade: "NOVA TRENTO", prazoEntrega: 3 },
  { cidade: "NOVA VENEZA", prazoEntrega: 2 },
  { cidade: "NOVO HORIZONTE", prazoEntrega: 2 },
  { cidade: "ORLEANS", prazoEntrega: 3 },
  { cidade: "OTACILIO COSTA", prazoEntrega: 2 },
  { cidade: "OURO", prazoEntrega: 3 },
  { cidade: "OURO VERDE", prazoEntrega: 3 },
  { cidade: "PAIAL", prazoEntrega: 3 },
  { cidade: "PAINEL", prazoEntrega: 3 },
  { cidade: "PALMA SOLA", prazoEntrega: 2 },
  { cidade: "PALMEIRA", prazoEntrega: 3 },
  { cidade: "PALMITOS", prazoEntrega: 2 },
  { cidade: "PARAISO", prazoEntrega: 3 },
  { cidade: "PASSO DE TORRES", prazoEntrega: 3 },
  { cidade: "PASSOS MAIA", prazoEntrega: 3 },
  { cidade: "PAULO LOPES", prazoEntrega: 3 },
  { cidade: "PEDRAS GRANDES", prazoEntrega: 3 },
  { cidade: "PENHA", prazoEntrega: 2 },
  { cidade: "PERITIBA", prazoEntrega: 3 },
  { cidade: "PESCARIA BRAVA", prazoEntrega: 3 },
  { cidade: "PETROLANDIA", prazoEntrega: 2 },
  { cidade: "PINHALZINHO", prazoEntrega: 2 },
  { cidade: "PINHEIRO PRETO", prazoEntrega: 2 },
  { cidade: "PIRATUBA", prazoEntrega: 3 },
  { cidade: "PLANALTO ALEGRE", prazoEntrega: 2 },
  { cidade: "POMERODE", prazoEntrega: 2 },
  { cidade: "PONTE ALTA", prazoEntrega: 2 },
  { cidade: "PONTE ALTA DO NORTE", prazoEntrega: 4 },
  { cidade: "PONTE SERRADA", prazoEntrega: 3 },
  { cidade: "PORTO BELO", prazoEntrega: 2 },
  { cidade: "POUSO REDONDO", prazoEntrega: 2 },
  { cidade: "PRAIA GRANDE", prazoEntrega: 3 },
  { cidade: "PRESIDENTE CASTELLO BRANCO", prazoEntrega: 3 },
  { cidade: "PRESIDENTE GETULIO", prazoEntrega: 2 },
  { cidade: "PRESIDENTE NEREU", prazoEntrega: 2 },
  { cidade: "PRINCESA", prazoEntrega: 3 },
  { cidade: "QUILOMBO", prazoEntrega: 2 },
  { cidade: "RANCHO QUEIMADO", prazoEntrega: 3 },
  { cidade: "RIO DAS ANTAS", prazoEntrega: 3 },
  { cidade: "RIO DO CAMPO", prazoEntrega: 2 },
  { cidade: "RIO DO OESTE", prazoEntrega: 2 },
  { cidade: "RIO DO SUL", prazoEntrega: 1 },
  { cidade: "RIO DOS CEDROS", prazoEntrega: 3 },
  { cidade: "RIO FORTUNA", prazoEntrega: 3 },
  { cidade: "RIO RUFINO", prazoEntrega: 3 },
  { cidade: "RIQUEZA", prazoEntrega: 2 },
  { cidade: "RODEIO", prazoEntrega: 2 },
  { cidade: "ROMELANDIA", prazoEntrega: 3 },
  { cidade: "SALETE", prazoEntrega: 2 },
  { cidade: "SALTINHO", prazoEntrega: 2 },
  { cidade: "SALTO VELOSO", prazoEntrega: 2 },
  { cidade: "SANGAO", prazoEntrega: 3 },
  { cidade: "SANTA CECILIA", prazoEntrega: 3 },
  { cidade: "SANTA HELENA", prazoEntrega: 3 },
  { cidade: "SANTA ROSA DE LIMA", prazoEntrega: 3 },
  { cidade: "SANTA ROSA DO SUL", prazoEntrega: 3 },
  { cidade: "SANTA TEREZINHA", prazoEntrega: 2 },
  { cidade: "SANTA TEREZINHA DO PROGRESSO", prazoEntrega: 3 },
  { cidade: "SANTIAGO DO SUL", prazoEntrega: 4 },
  { cidade: "SANTO AMARO DA IMPERATRIZ", prazoEntrega: 3 },
  { cidade: "SAO BERNARDINO", prazoEntrega: 3 },
  { cidade: "SAO BONIFACIO", prazoEntrega: 3 },
  { cidade: "SAO CARLOS", prazoEntrega: 2 },
  { cidade: "SAO CRISTOVAO DO SUL", prazoEntrega: 3 },
  { cidade: "SAO DOMINGOS", prazoEntrega: 2 },
  { cidade: "SAO JOAO BATISTA", prazoEntrega: 3 },
  { cidade: "SAO JOAO DO OESTE", prazoEntrega: 2 },
  { cidade: "SAO JOAO DO SUL", prazoEntrega: 3 },
  { cidade: "SAO JOAQUIM", prazoEntrega: 2 },
  { cidade: "SAO JOSE DO CEDRO", prazoEntrega: 2 },
  { cidade: "SAO JOSE DO CERRITO", prazoEntrega: 3 },
  { cidade: "SAO LOURENCO DO OESTE", prazoEntrega: 2 },
  { cidade: "SAO LUDGERO", prazoEntrega: 3 },
  { cidade: "SAO MARTINHO", prazoEntrega: 4 },
  { cidade: "SAO MIGUEL DA BOA VISTA", prazoEntrega: 3 },
  { cidade: "SAO MIGUEL DO OESTE", prazoEntrega: 2 },
  { cidade: "SAO PEDRO DE ALCANTARA", prazoEntrega: 3 },
  { cidade: "SAUDADES", prazoEntrega: 3 },
  { cidade: "SEARA", prazoEntrega: 2 },
  { cidade: "SERRA ALTA", prazoEntrega: 2 },
  { cidade: "SIDEROPOLIS", prazoEntrega: 3 },
  { cidade: "SOMBRIO", prazoEntrega: 2 },
  { cidade: "SUL BRASIL", prazoEntrega: 3 },
  { cidade: "TAIO", prazoEntrega: 2 },
  { cidade: "TANGARA", prazoEntrega: 3 },
  { cidade: "TIGRINHOS", prazoEntrega: 3 },
  { cidade: "TIJUCAS", prazoEntrega: 3 },
  { cidade: "TIMBE DO SUL", prazoEntrega: 3 },
  { cidade: "TIMBO", prazoEntrega: 3 },
  { cidade: "TIMBO GRANDE", prazoEntrega: 3 },
  { cidade: "TREVISO", prazoEntrega: 3 },
  { cidade: "TREZE DE MAIO", prazoEntrega: 3 },
  { cidade: "TREZE TILIAS", prazoEntrega: 3 },
  { cidade: "TROMBUDO CENTRAL", prazoEntrega: 2 },
  { cidade: "TUBARAO", prazoEntrega: 1 },
  { cidade: "TUNAPOLIS", prazoEntrega: 3 },
  { cidade: "TURVO", prazoEntrega: 2 },
  { cidade: "UNIAO DO OESTE", prazoEntrega: 3 },
  { cidade: "URUBICI", prazoEntrega: 2 },
  { cidade: "URUPEMA", prazoEntrega: 3 },
  { cidade: "URUSSANGA", prazoEntrega: 3 },
  { cidade: "VARGEAO", prazoEntrega: 4 },
  { cidade: "VARGEM", prazoEntrega: 3 },
  { cidade: "VARGEM BONITA", prazoEntrega: 3 },
  { cidade: "VIDAL RAMOS", prazoEntrega: 2 },
  { cidade: "VIDEIRA", prazoEntrega: 2 },
  { cidade: "VITOR MEIRELES", prazoEntrega: 2 },
  { cidade: "WITMARSUM", prazoEntrega: 2 },
  { cidade: "XANXERE", prazoEntrega: 2 },
  { cidade: "XAVANTINA", prazoEntrega: 3 },
  { cidade: "XAXIM", prazoEntrega: 2 },
  { cidade: "ZORTEA", prazoEntrega: 4 }
];

export const getPrazoByCidade = (cidade: string): number | null => {
  const cidadeUpper = cidade.toUpperCase();
  const prazo = prazosEntrega.find(p => p.cidade === cidadeUpper);
  return prazo ? prazo.prazoEntrega : null;
};

export default { prazosEntrega, getPrazoByCidade };